<div class="login-box radius_10">
    <h1>Administrator Login</h1>
    <p>
        This login process require three steps :
    </p>
    <ol>
        <li>Twitter Oauth Authentication</li>
        <li>User Existence Checking</li>
        <li>Two Factor Authentication (via DuoSecurity)</li>
    </ol>
    <p class="right">
        <a class="btn btn-small btn-success" href="<?php echo $this->url('duoauth-twitter-login');?>">
            Okay, lets start it <i class="icon-white icon-forward"></i>
        </a>
    </p>
</div>
<?php echo $this->render('du-oauth/_footnote'); ?>