<?php 
$host       = $this->host;
$sigRequest = $this->sig_request;
$postUrl    = $this->url('duoauth-duosecurity-responseverify');
$duoScript  =<<<EOH
Duo.init({
    'host': '$host',
    'post_action':'$postUrl',
    'sig_request': '$sigRequest'
});
EOH;
$jsFile = $this->url('duoauth-assets', array(
                        'file' => 'Duo-Web-v1.min.js'
                    ));

$this->headScript()->prependFile('//code.jquery.com/jquery-1.8.0.min.js');
$this->headScript()->appendFile($this->basePath() . '/assets/js/simukti-network.js');
$this->headScript()->appendFile($jsFile)
                   ->appendScript($duoScript);
?>

<div class="login-box radius_10">
    <h1>Administrator Verification</h1>
    <iframe id="duo_iframe" frameborder="0" allowtransparency="true" 
        style="background: transparent;width:100%;height:200px;overflow: hidden;">
    </iframe>
</div>
<?php echo $this->render('du-oauth/_footnote'); ?>